### ISSUE TITLE
Self-isolation end date disagrees with NHS Test & Trace, and NHS guidelines

### ISSUE THREAD

**Issue by colingreen** [nihp-public/covid19-app-system-public#32]
**Describe the bug**

The self-isolation end date in the app disagrees with the instructions sent by NHS Test & Trace by 1 day, and by the date implied by the NHS guidelines by 2 days.

**To Reproduce**

Develop symptoms on one day (say the 6th for example). Check the NHS guidelines for self-isolation, which suggest isolating until, and including the 16th.

Receive a positive PCR test result on the 8th, along with instructions to self-isolate until, and including the 17th.

Open the app to find a big flashing alert telling you to isolate until 23:59 on the 18th.

**Expected behavior**

A single, definitive date for the end of self-isolation.

**Screenshots**

![IMG_1104](https://user-images.githubusercontent.com/5745597/128829734-b79bb825-2ba9-4cf4-a8b9-2fa6f41cd93f.jpeg)
![BDDE91FA-A432-441B-AFD0-634517BB86E4](https://user-images.githubusercontent.com/5745597/128829756-e264b8e1-9089-4044-a7ac-8c09c560948b.jpg)
![BFC63060-2F41-4541-9930-2594376E8F5E](https://user-images.githubusercontent.com/5745597/128829766-ed111f83-7b13-4e09-8f77-2eb2100da854.jpg)

**Comment by nhs-covid19** [comment]
Thank you for your query relating to the self-isolation periods advised by the NHS COVID-19 app.
 
The NHS COVID-19 app complements NHS Test and Trace processes and policies. If you test positive for coronavirus (COVID-19) you must isolate for ten full days from the date you took your test.
 
Therefore, if a positive test was taken and entered into the app on the 8th of August, the app would advise self-isolation for the following ten full days following your test date (until 18th August). This is in line with the wider Test and Trace policy and the self-isolation period that would be mandated by them.
 
If, when you took your test, you were already self-isolating because you had coronavirus (COVID-19) symptoms, Test and Trace and the app both calculate your ten full days following the day your symptoms started.
 
Therefore, if you did not report your symptoms in the app, it does not know when your symptoms began and will use your test date to calculate your self-isolation period.
 
You can report your symptoms either by using the symptom checker on the app homepage, or when prompted by the app after you enter your positive test result.
